---
title: "DA401ProjDataWrangling"
author: "Jake Caldwell"
date: '2022-10-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library("dplyr")
library("tidyr")
library(rmarkdown)
library(randomForest)
library(ggplot2)
library(GGally)
library(caret)
library(tidyr)
library(knitr)
library(rgl)
library(dplyr)
library(ggfortify)
library(MASS)
library(e1071)
library(class)
library(cutpointr)
library(car)
library(boot)
library(tidyverse)           
library(ggthemes)
library(Hmisc)               
library(xtable)
library(pander)
library(kableExtra)
library(purrr)
```

```{r}
NBA <- data.frame() # creates an empty Data Frame
listcsv <- dir(pattern = "*SeasonStats.csv") # creates the list of all the csv files in the directory
for (k in 1:length(listcsv)){
 NBA <- rbind(NBA,read.csv(listcsv[k]))
}
# For Loop reads in each csv from my DA 401 project directory and binds it to the NBAData data frame, which creates a data frame containing all NBA player per game data from 1981 to 2022
```

```{r}
# Renaming variables and filtering data
NBA <- rename(NBA, "FGpct" = "FG.")
NBA <- rename(NBA, "eFGpct" = "eFG.")
NBA <- rename(NBA, "ThP" = "X3P")
NBA <- rename(NBA, "ThPA" = "X3PA")
NBA <- rename(NBA, "ThPpct" = "X3P.")
NBA <- rename(NBA, "TwP" = "X2P")
NBA <- rename(NBA, "TwPA" = "X2PA")
NBA <- rename(NBA, "TwPpct" = "X2P.")
NBA <- rename(NBA, "FTpct" = "FT.")
NBA <- rename(NBA, "Player" = "ï..Player")
NBA[is.na(NBA)] <- 0
NBA<-filter(NBA, NBA$G > 20)
NBA <- filter(NBA, NBA$Pos %in% c('PG', 'SG', 'SF', 'PF', 'C'))
```

```{r} 
#Creating variables I need for calculating the PER statistic
factor <- (2/3) - ((0.5 * (21.8/37.3))/(2 * (37.3/18.8)))
VOP <- 99.9/(81.5 - 11.2 + 14.1 + (0.44*24.9))
DRBpct <- (42.0-11.2)/42.0
factor
VOP
DRBpct
```


```{r}
#Creation of GameScore and PER
NBA<- NBA%>%mutate(GameScore = NBA$PTS + 0.4*NBA$FG - 0.7*NBA$FGA - 0.4*(NBA$FTA - NBA$FT) + 0.7*NBA$ORB + 0.3*NBA$DRB +0.7*NBA$STL + 0.7*NBA$AST + 0.7*NBA$BLK - 0.4*NBA$PF - NBA$TOV)

#Unadjusted PER
NBA <- NBA %>% mutate(uPER = (1/MP)*(ThP- ((PF*18.8)/21) +((FT/2)*(2-(21.8/(3*37.3))))+(FG * (2-((factor*21.8)/37.3)))+((2*AST)/3) +(VOP)+(DRBpct*((2*ORB)+BLK-(0.2464*(FTA-FT))-(FGA-FG)                  -TRB)+((0.44*24.9*PF)/21)-(TOV+ORB)+STL+TRB-(.1936*(FTA-FT)))))
                        

#Adjusted PER
NBA <- NBA %>% mutate(aPER = 1.01*uPER)
NBA[is.na(NBA)] <- 0

#Final PER
NBA <- NBA %>% mutate(PER = aPER * (15/mean(NBA$aPER)))
```

```{r}
#Summary Statistics on Variables of Importance 
library("vtable")
st(NBA, vars = c('Age', 'PTS', 'AST', 'TRB', 'FGpct', 'TOV', 'PF', 'BLK', 'STL', 'FTpct', 'GameScore', 'PER'))
```

```{r} 
#Writing cleaned and wrangled CSV to put into tableau
write.csv(NBA,"NBA.csv", row.names = FALSE)
```

```{r}
library('ggplot2')
library('ggthemes')
#Creating histograms and density plots for GameScore and PER
GameScoreDist <- NBA %>% ggplot(aes(x=GameScore))+
  geom_histogram(bins = 10, fill = 'blue', color = '#000000', aes(y = ..density..))+
  geom_density(fill = "#F85700", color = "#000000", alpha = 0.6)+
  labs(title = "Distribution of \n GameScore", x = 'GameScore', y = 'Frequency')+
  geom_vline(aes(xintercept = mean(GameScore)), color = "#000000", size = 1.25) +
  geom_vline(aes(xintercept = mean(GameScore) + 2*sd(GameScore)), color = "#000000", size = 1, linetype = "dashed") +
  theme_classic()+
theme(title = element_text(size = 28), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text = element_text(size = 16))

PERDist <- NBA %>% ggplot(aes(x=PER))+
  geom_histogram(bins = 10, fill = 'blue', color = '#000000', aes(y = ..density..))+
  geom_density(fill = "#F85700", color = "#000000", alpha = 0.6)+
  labs(title = "Distribution of PER", x = 'PER', y = 'Frequency')+
  geom_vline(aes(xintercept = mean(PER)), color = "#000000", size = 1.25) +
  geom_vline(aes(xintercept = mean(PER) + 2*sd(PER)), color = "#000000", size = 1, linetype = "dashed") +
  theme_classic()+
theme(title = element_text(size = 28), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20), axis.text.x = element_text(size = 16), axis.text = element_text(size = 16))
  

png("PERDist.png")
print(PERDist)
dev.off
```
```{r}
png("GameScoreDist.png")
print(GameScoreDist)
dev.off
```


```{r}
# Creating dataframe of career averages for PER and GameScore

CareerAvgPER <- NBA %>% dplyr::select(Player, Pos, PER) %>% group_by(Player) %>% summarise('PER' = mean(PER))
CareerAvgGameScore <- NBA %>% dplyr::select(Player, Pos, GameScore) %>% group_by(Player) %>% summarise('GameScore' = mean(GameScore))

# Select the top 50 players using career PER and GameScore

topPER <- head(sort(CareerAvgPER$PER, decreasing = TRUE), n = 50)
topGameScore <- head(sort(CareerAvgGameScore$GameScore, decreasing = TRUE), n = 50)

# Table Results

top50PER <- CareerAvgPER[CareerAvgPER$PER %in% topPER,]
top50GameScore <- CareerAvgGameScore[CareerAvgGameScore$GameScore %in% topGameScore, ]
```

```{r}
#Create List of NBA 75 Players 
NBA75 <- read.csv("NBA75.csv")
NBA75 <- rename(NBA75, "Player" = "ï..Player")
```

```{r}
#Creating Similarity Venn diagrams for the NBA75 team to the top Career PER and GameScore.

both1 <- top50PER[top50PER$Player %in% NBA75$Player,] # in both, same as call: intersect(first, second)
onlyfirst1 <-top50PER[!top50PER$Player %in% NBA75$Player,] # only in 'first', same as: setdiff(first, second)
onlysecond1 <- NBA75[!NBA75$Player %in% top50PER$Player,] # only in 'second', same as: setdiff(second, first)
length(both1)
length(onlyfirst1)
length(onlysecond1)


# If you don't have the 'gplots' package, type: install.packages("gplots")
require("gplots")
venn(list(first.vector = top50PER$Player, second.vector = NBA75$Player))

both2 <- top50GameScore[top50GameScore$Player %in% NBA75$Player,] # in both, same as call: intersect(first, second)
onlyfirst2 <-top50GameScore[!top50GameScore$Player %in% NBA75$Player,] # only in 'first', same as: setdiff(first, second)
onlysecond2 <- NBA75[!NBA75$Player %in% top50GameScore$Player,] # only in 'second', same as: setdiff(second, first)
length(both2)
length(onlyfirst2)
length(onlysecond2)


# If you don't have the 'gplots' package, type: install.packages("gplots")
require("gplots")
venn(list(first.vector = top50GameScore$Player, second.vector = NBA75$Player))
```

```{r}
#Different way to make the venn diagrams
library('ggvenn')
library('RColorBrewer')
lPER <- top50PER$Player
lGameScore <- top50GameScore$Player
lNBA75 <- NBA75$Player

x <- list(lPER=lPER, lGameScore=lGameScore, lNBA75=lNBA75)

listVD <- ggvenn(x, show_elements = F, label_sep = '\n', fill_color = brewer.pal(name = "Set2", n=3), text_size = 6)
png("listVD.png")
print(listVD)
dev.off
```

```{r}
#Creating Training and Test Sets
set.seed(1)
# We use the dataset to create a partition (70% training 30% testing)
index <- createDataPartition(NBA$PER, p=0.70, list=FALSE)

# select 70% of data to train the models
training <- NBA[index,]
train.x <- data.frame(training[,-34]) 
train.y <- training$PER


# select 30% of the data for testing
test <- NBA[-index,]
test.x <- data.frame(test[,-34]) 
test.y <- test$PER
```

```{r}
library(tree)
tree.PER <- tree(PER~PTS+AST+TRB+FGpct+Age+FTpct+TOV+PF+STL+BLK, data = NBA)
plot(tree.PER)
text(tree.PER)
```

```{r}
library(tree)
tree.GameScore <- tree(GameScore~PTS+AST+FGpct+Age+FTpct+PF+TOV+STL+BLK, data = NBA)
plot(tree.GameScore)
text(tree.GameScore)
```


```{r}
trees <- c(5,10,20,50,300, 500)
mseV <- c()
for(i in trees){
  rfmodel <- randomForest(PER~PTS+AST+TRB+Age+FGpct+FTpct, data = training, mtry = 2, na.action = na.exclude, ntree = i)
  preds <- predict(rfmodel, test.x)
  preddf <- data.frame(preds, test.y)
  preddf <- na.omit(preddf)
  mse <- (mean((preddf$preds-preddf$test.y)^2))/1e+12
  mseV <- c(mseV, mse)
}
which.min(mseV)
mseV[7]
```

